# run > ollama list to view available models
ORCA2 = "orca2:latest"
QWEN = "qwen2:latest"
PHI3 = "phi3:medium"
GEMMA = "gemma:7b"
GEMMA_LATEST = "gemma:latest"
LLAMA3 = "llama3:latest"
LLAMA2 = "llama2:latest"
LLTEXT = "llama3:text"
MISTRAL = "mistral:latest"
MISTRAL_OPENORCA = "mistral-openorca:latest"
MIXTRAL = "mixtral:latest"
WIZARD = "wizard-vicuna-uncensored:13b"
